[pytest]
filterwarnings =
    ignore:.*'oneOf' deprecated - use 'one_of'.*:pyparsing.exceptions.PyparsingDeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:.*'parseString' deprecated - use 'parse_string'.*:pyparsing.exceptions.PyparsingDeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:.*'resetCache' deprecated - use 'reset_cache'.*:pyparsing.exceptions.PyparsingDeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:.*'enablePackrat' deprecated - use 'enable_packrat'.*:pyparsing.exceptions.PyparsingDeprecationWarning:matplotlib\._mathtext
